# Default (local MongoDB)
spring:
  config:
    activate:
      on-profile: default
  banner:
    location: banner-dev.txt
  data:
    mongodb:
      uri: mongodb://127.0.0.1:27017/cookie-contacts
  application:
    name: Cookie Contacts
---

# Dev Database Properties (local MongoDB)
spring:
  banner:
    location: banner-dev.txt
  data:
    mongodb:
      uri: mongodb://127.0.0.1:27017/cookie-contacts
  application:
    name: Cookie Contacts
  config:
    activate:
      on-profile: dev
  jpa:
    hibernate:
      ddl-auto: none
---

# Prod Database Properties (cloud MongoDB)
spring:
  banner:
    location: banner-prod.txt
  data:
    mongodb:
      uri: mongodb+srv://cookie:${spring.data.mongodb.password}@cluster0.smlnt.mongodb.net/?retryWrites=true&w=majority
      password: ???
      database: cookie-contacts
  application:
    name: Cookie Contacts
  config:
    activate:
      on-profile: prod
  jpa:
    hibernate:
      ddl-auto: none
